Consider SCROLL_AMOUNT into the mouse wheel scroll condition
oberonamsterdam/horizontal pull request #26
Opened 2020-08-17 20:18 UTC by maximedaoust

related to #25

2020-08-24 19:14 UTC, arguiot commented
I've tested the changes myself and it works very well. I hope this PR will be merged very soon

2020-12-07 14:28 UTC, matthijsoberon requested changes
Thanks for contributing, good job :). I've given some feedback on your PR, will merge it after you've updated it!

2020-12-07 14:28 UTC, matthijsoberon commented on src/index.ts
> +        if (distance - SCROLL_AMOUNT < this.container.scrollWidth - this.container.clientWidth) {
Hey, thanks for contributing! Works fine, but this should be changed to the `scrollAmount` that's passed to the constructor so it takes the actual scrollAmount that's configured. Which is by default equal to the `SCROLL_AMOUNT` variable, but this makes it more dynamic.

2021-01-04 12:34 UTC, matthijsoberon commented on src/index.ts
> +        if (distance - SCROLL_AMOUNT < this.container.scrollWidth - this.container.clientWidth) {
Resolved in PR #32

2021-01-04 12:34 UTC, matthijsoberon commented
Duplicate of #32

2021-01-04 12:34 UTC, closed without merging